#define QUICKBMS_VER_ZERO   0
#define QUICKBMS_VER_MAJ    7
#define QUICKBMS_VER_MIN    6
#define QUICKBMS_VER_FIX    0x61
#define QUICKBMS_VER        QUICKBMS_VER_ZERO,QUICKBMS_VER_MAJ,QUICKBMS_VER_MIN,QUICKBMS_VER_FIX
#define QUICKBMS_VER_STR    ""#QUICKBMS_VER_ZERO#"."#QUICKBMS_VER_MAJ#"."#QUICKBMS_VER_MIN#"."#QUICKBMS_VER_FIX#""
